@startuml app
component "App.Run" {

    ' The data package contains the core business logic
    ' used by the App.Run function
    package "data" {
        [WorkflowRunController] as wfc
        wfc ..> StateMachine
        [NewStateMachine] ..> StateMachine
        [NewStateMachine] ..> Marshaller
        [NewStateMachine] ..> Publisher
    }

    wfc ..> WorkflowRunner
    package "engine" {
        [InProcessWorkflowRunner] -up.> WorkflowRunner
    }

    wfc ..> Publisher
    package "messaging" {
        [StanPublisher] -up..> Publisher
    }

    wfc ..> Marshaller
    package "serialization" {
        [JSON] -up..> Marshaller
    }

    wfc -d-> [XMLs]

    wfc ..> AssetPathResolver
}
@enduml